### ISSUE TITLE
EMLPaser Servlet doesn't work on the 2.2 branch

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/eml#331]
I used the command "ant emlpaser_war"  to build an emlparser.war file on the 2.2 branch and dropped it on my local tomcat webapps directory.  However, when I tried to parse an eml documents, I got this error:
```type Exception report

message Servlet execution threw an exception

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: Servlet execution threw an exception
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
root cause

java.lang.NoClassDefFoundError: edu/ucsb/nceas/utilities/config/ConfigXML
	org.ecoinformatics.eml.SAXValidate.runTest(SAXValidate.java:113)
	org.ecoinformatics.eml.EMLParserServlet.parse(EMLParserServlet.java:244)
	org.ecoinformatics.eml.EMLParserServlet.handleGetOrPost(EMLParserServlet.java:178)
	org.ecoinformatics.eml.EMLParserServlet.doPost(EMLParserServlet.java:109)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
root cause

java.lang.ClassNotFoundException: edu.ucsb.nceas.utilities.config.ConfigXML
	org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720)
	org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
	org.ecoinformatics.eml.SAXValidate.runTest(SAXValidate.java:113)
	org.ecoinformatics.eml.EMLParserServlet.parse(EMLParserServlet.java:244)
	org.ecoinformatics.eml.EMLParserServlet.handleGetOrPost(EMLParserServlet.java:178)
	org.ecoinformatics.eml.EMLParserServlet.doPost(EMLParserServlet.java:109)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
```

**Comment by mbjones** [comment]
Added the utilities.jar back into the emlparser.war file to fix the problem with ConfigXML not being found.

Now the servlet parses both 2.2.0 and 2.1.1 docs properly.  The one challenge is that the namespaces for the 2.1.1 and before releases points at the emlparser deploy itself, which is currently configured for the KNB deployment.  As long as it gets deployed there, things should be fine.  If we deploy it elsewhere, we'll need to update the schema locations in the config.xml configuration file.

**Comment by mbjones** [comment]
@taojing2002 please review and see if this looks like it will work for deployment to you.  Thanks.
